version: 1.0.{build}
image:
- Visual Studio 2015
- Ubuntu

for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - cd "enet server test"
  - g++ -o "enet server test" "enet server test.cpp" -std=c++11 -lenet
